using BepInEx.Bootstrap;
using RiskyMonkeyBase.LangDynamic.Items;
using RiskyMonkeyBase.Tweaks;
using System.Collections.Generic;

namespace RiskyMonkeyBase.LangDynamic
{
    public class BetterDesc
    {
        public static List<ItemModProfile> profiles;
        public static Dictionary<string, string> keyRepl;

        public static void Patch()
        {
            if (!Reference.UseFullDescForPickup.Value) return;
            profiles = new List<ItemModProfile>();
            keyRepl = new Dictionary<string, string>();

            // vanilla
            profiles.Add(new ItemModProfile("", "ITEM_{0}_{1}", "PICKUP", "DESC").Add("CLOVER", "SYRINGE", "BEAR", "BEHEMOTH", "MISSILE", "EXPLODEONDEATH", "DAGGER", "TOOTH", "CRITGLASSES", "HOOF", "FEATHER", "CHAINLIGHTNING", "SEED", "ICICLE", "GHOSTONKILL", "MUSHROOM", "CROWBAR", "ATTACKSPEEDONCRIT", "BLEEDONHIT", "SPRINTOUTOFCOMBAT", "FALLBOOTS", "COOLDOWNONCRIT", "WARDONLEVEL", "WARCRYONMULTIKILL", "PHASING", "HEALONCRIT", "HEALWHILESAFE", "JUMPBOOST", "PERSONALSHIELD", "NOVAONHEAL", "MEDKIT", "EQUIPMENTMAGAZINE", "INFUSION", "SHOCKNEARBY", "IGNITEONKILL", "BOUNCENEARBY", "FIREWORK", "BANDOLIER", "STUNCHANCEONHIT", "LUNARDAGGER", "GOLDONHIT", "SHIELDONLY", "ALIENHEAD", "TALISMAN", "KNURL", "BEETLEGLAND", "SPRINTBONUS", "SECONDARYSKILLMAGAZINE", "STICKYBOMB", "TREASURECACHE", "BOSSDAMAGEBONUS", "SPRINTARMOR", "ICERING", "FIRERING", "SLOWONHIT", "EXTRALIFE", "EXTRALIFECONSUMED", "UTILITYSKILLMAGAZINE", "HEADHUNTER", "KILLELITEFRENZY", "INCREASEHEALING", "REPEATHEAL", "AUTOCASTEQUIPMENT", "EXECUTELOWHEALTHELITE", "ENERGIZEDONEQUIPMENTUSE", "BARRIERONOVERHEAL", "TONICAFFLICTION", "TITANGOLDDURINGTP", "SPRINTWISP", "BARRIERONKILL", "ARMORREDUCTIONONHIT", "TPHEALINGNOVA", "NEARBYDAMAGEBONUS", "LUNARUTILITYREPLACEMENT", "PROTECTIONPOTION", "THORNS", "FLATHEALTH", "PEARL", "SHINYPEARL", "BONUSGOLDPACKONKILL", "LASERTURBINE", "LUNARPRIMARYREPLACEMENT", "NOVAONLOWHEALTH", "LUNARTRINKET", "REPULSIONARMORPLATE", "SQUIDTURRET", "DEATHMARK", "INTERSTELLARDESKPLANT", "ANCESTRALINCUBATOR", "FOCUSEDCONVERGENCE", "FIREBALLSONHIT", "LIGHTNINGSTRIKEONHIT", "BLEEDONHITANDEXPLODE", "SIPHONONLOWHEALTH", "MONSTERSONSHRINEUSE", "RANDOMDAMAGEZONE", "ARTIFACTKEY", "CAPTAINDEFENSEMATRIX", "SCRAPWHITE", "SCRAPGREEN", "SCRAPRED", "SCRAPYELLOW", "LUNARBADLUCK", "LUNARSECONDARYREPLACEMENT", "ATTACKSPEEDANDMOVESPEED", "PRIMARYSKILLSHURIKEN", "CRITDAMAGE", "DRONEWEAPONS", "MOVESPEEDONKILL", "STRENGTHENBURN", "HEALINGPOTION", "HEALINGPOTIONCONSUMED", "PERMANENTDEBUFFONHIT", "MOREMISSILE", "SKULLCOUNTER", "ROBOBALLBUDDY", "PARENTEGG", "LUNARSPECIALREPLACEMENT", "HALFSPEEDDOUBLEHEALTH", "HALFATTACKSPEEDHALFCOOLDOWNS", "LUNARWINGS", "RANDOMLYLUNAR", "IMMUNETODEBUFF", "REGENERATINGSCRAP", "REGENERATINGSCRAPCONSUMED", "CRITGLASSESVOID", "EXPLODEONDEATHVOID", "BLEEDONHITVOID", "TREASURECACHEVOID", "BEARVOID", "CLOVERVOID", "MISSILEVOID", "MUSHROOMVOID", "SLOWONHITVOID", "CHAINLIGHTNINGVOID", "EQUIPMENTMAGAZINEVOID", "EXTRALIFEVOID", "EXTRALIFEVOIDCONSUMED", "FRAGILEDAMAGEBONUS", "FRAGILEDAMAGEBONUSCONSUMED", "OUTOFCOMBATARMOR", "SCRAPWHITESUPPRESSED", "SCRAPGREENSUPPRESSED", "SCRAPREDSUPPRESSED", "GOLDONHURT", "RANDOMEQUIPMENTTRIGGER", "FREECHEST", "ELEMENTALRINGVOID", "LUNARSUN", "MINORCONSTRUCTONKILL", "VOIDMEGACRABITEM"));

            // bubbets
            profiles.Add(new ItemModProfile("bubbet.bubbetsitems", "{0}_{1}", "PICKUP", "DESC_SIMPLE").Add("JELLIEDSOLES", "GEMCARAPACE", "CLAYCATALYST", "BONEVISOR", "HEAL_FROM_DOT_INFLICTED", "BUNNYFOOT", "ESCAPE_PLAN", "TIMED_BUFF_DURATION", "CEREMONIALPROBE", "DECREASEBARRIERDECAY", "ETERNALSLUG", "ACIDSOAKEDBLINDFOLD", "VOIDJUNKTOSCRAPTIER1", "RECURSIONBULLETS", "SHIFTEDQUARTZ", "SCINTILLATINGJET", "VOIDSLUG", "VOIDHOURGLASS", "ZEALOTRYEMBRACE", "VOIDBLINDFOLD", "SUBMERGINGCISTERN", "ABSTRACTEDLOCUS", "CIRCLET", "CLUMPEDSAND", "DECENT", "HYDROPHILY", "IMPERFECT", "ORBOFFALSITY", "SEEPINGOCEAN", "TARNISHED"));

            // stormy
            profiles.Add(new ItemModProfile("Quickstraw.StormyItems", "ITEM_{0}_{1}", "PICKUP", "DESCRIPTION").Add("CRACKED_HALO", "SHARP_ANCHOR", "ABYSSAL_TALON", "ILLEGAL_DRONE_COOLANT", "CHARGED_URCHIN"));

            // vanillavoid
            profiles.Add(new ItemModProfile("com.Zenithrium.vanillaVoid", "VV_ITEM_{0}_{1}", "PICKUP", "DESCRIPTION").Add("ADZE_ITEM", "BARRIERLOTUS_ITEM", "CLOCKWORK_ITEM", "EHANCE_VIALS_ITEM", "DASHQUILL_ITEM", "CRYOCANISTER_ITEM", "WICKEDSTAFF_ITEM", "EXEBLADE_ITEM", "EXT_EXHAUST_ITEM", "ORRERY_ITEM"));

            // hcfb
            profiles.Add(new ItemModProfile("com.Ner0ls.HolyCrapForkIsBack", "HCFB_ITEM_{0}_{1}", "PICKUP", "DESC").Add("FORK", "SPOON", "SPORK", "KNIFE", "CHOPSTICKS", "MOLTEN_FORK", "BULWARK_SPOON", "OBSIDIAN_KNIFE"));

            // zetaspects
            profiles.Add(new ItemModProfile("com.TPDespair.ZetAspects", "ITEM_{0}_{1}", "PICKUP", "DESC").Add("ZETASPECTWHITE", "ZETASPECTBLUE", "ZETASPECTRED", "ZETASPECTHAUNTED", "ZETASPECTPOISON", "ZETASPECTLUNAR", "ZETASPECTEARTH", "ZETASPECTVOID", "ZETASPECTSANGUINE", "ZETASPECTSEPIA", "ZETASPECTGOLD", "ZETASPECTPLATED", "ZETASPECTWARPED", "ZETASPECTVEILED", "ZETASPECTARAGONITE", "ZETASPECTBLIGHTED"));

            // goldencoastplus
            profiles.Add(new ItemModProfile("com.Skell.GoldenCoastPlus", "{0}_{1}", "PICKUP", "DESC").Add("BIGSWORD", "GOLDENKNURL", "LASEREYE"));

            // forgottenrelic
            profiles.Add(new ItemModProfile("PlasmaCore.ForgottenRelics", "ITEM_{0}_{1}", "PICKUP", "DESC").Add("RELICENERGY", "SUNBLADE", "SAGESBOOK", "ESSENCEOFTAR", "VOIDSTOMPERS"));

            RiskyMonkeyBase.Log.LogInfo("[[Better item descriptions]] module loaded");
            foreach (var profile in profiles)
            {
                if (profile.GUID != "" && !Chainloader.PluginInfos.ContainsKey(profile.GUID)) continue;
                RiskyMonkeyBase.Log.LogInfo("Changing Desc for " + profile.GUID);
                foreach (var name in profile.Names)
                    keyRepl.Add(string.Format(profile.Format, name, profile.PickupName), string.Format(profile.Format, name, profile.DescName));
            }
            if (Chainloader.PluginInfos.ContainsKey("bubbet.bubbetsitems")) VoidLunarTweaks.handleRepulsionMK2();
            if (keyRepl.Keys.Count > 0) On.RoR2.Language.GetLocalizedStringByToken += (orig, self, token) =>
            {
                if (keyRepl.ContainsKey(token)) return orig(self, keyRepl[token]);
                return orig(self, token);
            };
        }
    }
}